version: '1.3'
services:
  database:
    image: postgres:15.2
    ports:
      - 5435:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=gofinancial
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate:v4.15.2
    profiles: [ "tools" ]
    volumes:
      - ./database/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://root:password@database:5432/gofinancial?sslmode=disable"
      ]
    command: [ "up" ]
    depends_on:
      database:
        condition: service_healthy
volumes:
  data:
